channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - colorama=0.4.6
  - cryptography=39.0.1
  - cuda-cccl=12.1.109
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=1.2.0
  - freetype=2.12.1
  - giflib=5.2.1
  - idna=3.4
  - importlib_metadata=6.8.0
  - intel-openmp=2023.1.0
  - ipykernel=6.15.0
  - ipython=8.14.0
  - jedi=0.18.2
  - jpeg=9e
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcurand=10.3.2.106
  - libcurand-dev=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.17
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - nest-asyncio=1.5.6
  - numpy-base=1.24.3
  - openssl=3.0.9
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pywin32=305
  - pyzmq=25.1.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.9.0
  - typing_extensions=4.6.3
  - tzdata=2023c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.6
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - argcomplete==3.1.1
      - async-timeout==4.0.2
      - attrs==22.2.0
      - autopep8==2.0.2
      - boto==2.49.0
      - cachetools==5.3.0
      - charset-normalizer==3.0.1
      - cloudpickle==2.2.1
      - contourpy==1.0.7
      - crcmod==1.7
      - cyanure==1.0.0
      - cycler==0.11.0
      - cython==0.29.34
      - dictances==1.5.6
      - fasteners==0.18
      - fonttools==4.39.3
      - frozenlist==1.3.3
      - fsspec==2023.3.0
      - gcs-oauth2-boto-plugin==3.0
      - google-apitools==0.5.32
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - google-reauth==0.1.1
      - grpcio==1.51.1
      - gsutil==5.24
      - gym==0.26.2
      - gym-notices==0.0.8
      - h5py==3.8.0
      - hdbscan==0.8.29
      - httplib2==0.20.4
      - hydra-core==1.3.2
      - importlib-metadata==6.0.0
      - importlib-resources==5.12.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - learn2learn==0.2.0
      - lightly==1.3.2
      - lightly-utils==0.0.2
      - lightning-utilities==0.8.0
      - llvmlite==0.40.1rc1
      - markdown==3.4.1
      - markupsafe==2.1.2
      - matplotlib==3.5.3
      - monotonic==1.6
      - multidict==6.0.4
      - numba==0.57.0
      - numpy==1.24.1
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.7.0.68
      - ordered-set==4.1.0
      - packaging==23.0
      - pandas==1.5.3
      - protobuf==3.20.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycodestyle==2.10.0
      - pynndescent==0.5.10
      - pyparsing==3.0.9
      - pytz==2022.7.1
      - pyu2f==0.1.5
      - pyyaml==6.0
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - retry-decorator==1.1.1
      - rsa==4.7.2
      - scikit-learn==1.2.1
      - scipy==1.10.0
      - seaborn==0.12.2
      - setuptools==65.0.0
      - submitit==1.4.5
      - support-developer==1.0.5
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - threadpoolctl==3.1.0
      - tomli==2.0.1
      - torch-tb-profiler==0.4.1
      - torchaudio==0.13.1
      - torchmetrics==0.11.4
      - torchvision==0.14.1
      - tqdm==4.64.1
      - typing-extensions==4.4.0
      - umap-learn==0.5.3
      - urllib3==1.26.14
      - werkzeug==2.2.2
      - wincertstore==0.2
      - yarl==1.8.2
      - zipp==3.12.0
